#!/usr/bin/env bash

set -e

function clean_exit {
 git checkout master
 git branch -D deploy
}
trap cleanup_exit EXIT

git checkout -b deploy
webpack -p
git add -f public/bundle.js public/bundle.js.map
git commit --allow-empty -m 'Deploy'
git push --force heroku deploy:master